# Generated by Django 4.0.2 on 2022-02-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prefix',
        ),
    ]
