# Generated by Django 4.0.2 on 2022-02-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='battery_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='brakefluid_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='brakefront_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='brakerear_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='bulb_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cabinfilter_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='coolant_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='differential_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='drivebelt_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='electrical_investigation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='enginefilter_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='exahust_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='fuelfilter_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='major_repairs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='mechanical_investigation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='oil_change',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='other_services',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='powersteering_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sparkplug_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='steering_repair',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='suspension_repair',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tire_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tire_rotation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='transfercase_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='transmission_service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='wiperblade_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
