# Generated by Django 4.0.2 on 2022-02-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_logs', '0002_service_battery_service_service_brakefluid_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='other_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
