# Generated by Django 4.0.2 on 2022-02-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_logs', '0007_alter_service_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_date',
        ),
    ]
