# Generated by Django 4.0.2 on 2022-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_logs', '0008_remove_service_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateField(auto_now=True),
        ),
    ]
