# Generated by Django 4.0.2 on 2022-03-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_logs', '0013_alter_service_shop_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='shop_city',
        ),
        migrations.RemoveField(
            model_name='service',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='shop_state',
        ),
        migrations.RemoveField(
            model_name='service',
            name='shop_street',
        ),
        migrations.RemoveField(
            model_name='service',
            name='shop_zipcode',
        ),
    ]
