# Generated by Django 4.0.2 on 2022-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicle_engine_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_size',
            field=models.CharField(choices=[('4', '4 Cylinder'), ('6', '6 Cylinder'), ('8', '8 Cylinder'), ('10', '10 Cylinder'), ('12', '12 Cylinder'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
