# Generated by Django 4.0.2 on 2022-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_engine_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drive_type',
            field=models.IntegerField(choices=[('4', 'AWD'), ('4', '4WD'), ('2', 'FWD'), ('2', 'RWD')], null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT')], max_length=50, null=True),
        ),
    ]
