# Generated by Django 4.0.2 on 2022-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(choices=[('AWD', 'AWD'), ('4WD', '4WD'), ('FWD', 'FWD'), ('RWD', 'RWD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_size',
            field=models.CharField(choices=[('4 Cylinder', '4 Cylinder'), ('6 Cylinder', '6 Cylinder'), ('8 Cylinder', '8 Cylinder'), ('10 Cylinder', '10 Cylinder'), ('12 Cylinder', '12 Cylinder'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
