# Generated by Django 4.0.2 on 2022-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_vehicle_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
